- constants/errors.js
- services/lnd/lightning.js
- src/server.js
Fixes "Macaroon file not found" error in [Wizard](https://github.com/shocknet/Wizard) and adds detailed error messages for LND certificates/macaroon not found
> Macaroon file bug fixes

- src/routes.js
> Added logoff on auth route and improves on error handling

- services/Mediator/index.js
- services/gunDB/contact-api/utils.js
- services/gunDB/index.js
- services/lnd/event-constants.js
- services/lnd/lnd.js
- src/routes.js
- src/sockets.js
- created index.js for gunDB folder
- moved only Mediator class, with important functions one level up
- updated imports
> Moved the gunDB mediator one level up in the dir tree

- src/routes.js
sat per byte param for sendcoins, openchannel,closechannel
> fees settings + java error fix

- .gitignore
- config/log.js
- yarn.lock
Same as #102 but includes formatted and colorized logs
> Winston Upgrade

- config/log.js
- package.json
- yarn.lock
Upgrades following dependencies:
```
"winston": "^3.3.3",
"winston-daily-rotate-file": "^4.5.0"
```
> Upgrade winston to v3.3.3

- src/routes.js
- src/server.js
Encrypts the Authorization header (Fixes #88)
> Backwards-compatible encrypted token functionality

- src/routes.js
> auth token in header for GET + skip hook cuz routes.js not pretty

- src/routes.js
Removed the channel backups error and made the backup stream re-connect every 30 seconds on connection drop
> Removed Channel Backups error

- main.js
- src/server.js
add api version to response headers
> add api version to response headers

- utils/lndJobs.js
> Revert "tip amount in new location"

- .github/workflows/version.yml
A GitHub action that upgrades the version in `package.json` if the latest release differs.
> Add version bump GitHub action

- .github/workflows/version.yml
Use single quote in version action
> Use single quote in version action

- .github/workflows/version.yml
Pass release tag as a environment variable in version action
P.S: Tested on https://github.com/gobeer/horde/actions
> Pass release tag as env var in version action

- src/routes.js
- utils/protectedRoutes.js
Add tunnel address public endpoint
> Add tunnel address public endpoint

- services/gunDB/contact-api/actions.js
> orderAck.response no longer a JSON

- Dockerfile
- README.md
Add new Dockerfile and usage guide
> Add new Dockerfile and usage guide

- README.md
> Add volumes to Docker README

- .github/workflows/dockerhub.yml
> Add docker hub action

- proto/autogenerated/client.md
- proto/autogenerated/debug.txt
- proto/autogenerated/ts/types.ts
- proto/service/structs.proto
- src/services/main/appUserManager.ts
- src/services/main/applicationManager.ts
Removed the bridge integration. Now the pull only is about making getuserInfo return user identifier as well
> getUserInfo returns user_identifier as well

- .gitignore
- env.example
- metricsDatasource.js
- src/auth.ts
- src/custom-nip19.ts
- src/nostrMiddleware.ts
- src/services/main/index.ts
- src/services/main/settings.ts
- src/services/nostr/handler.ts
- src/services/storage/db.ts
- src/services/storage/index.ts
- src/services/storage/metricsStorage.ts
- src/services/storage/migrations/runner.ts
The new db for metrics + env toggle for attaching the addMetrics call + don't log private key and log nprofile instead
> Standalone metrics db
